models_config:
  GCN:
    n_hidden: 64
    p_dropout: 0.8

  GAT:
    n_hidden: 64
    n_heads: 8
    p_dropout: 0.6
    p_dropout_attention: 0.3

  SAGE:
    n_hidden: 64
    p_dropout: 0.4

  APPNPNet:
    n_hidden: 64
    p_dropout: 0.5
    alpha: 0.1
    k: 10



